# rbac/rolebinding-devops.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: olivier-access
  namespace: odoo
subjects:
- kind: User
  name: olivier
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: odoo-full-access
  apiGroup: rbac.authorization.k8s.io